blueprints/home.py
from flask import Blueprint, render_template, request, redirect, url_for, jsonify, Response, flash
from flask_login import login_required
from db import db
from models import Agendamentos, Divergencias, Trocas, Devolucoes, Recebimento, Fornecedores
from datetime import datetime
from werkzeug.utils import secure_filename
import os

ALLOWED_EXTENSIONS = {'pdf'}

home_bp = Blueprint('home', __name__)
login_bp = Blueprint('login', __name__)

def allowed_file(filename):
    allowed_extensions = {'pdf'}
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in allowed_extensions


@home_bp.route('/suggestions')
def suggestions():
    termo = request.args.get('termo', '')
    if termo:
        fornecedores = db.session.query(Fornecedores.fornecedCnpj, Fornecedores.fornecedRazaoSocial).filter(Fornecedores.fornecedCnpj.like(f'%{termo}%')).all()
        suggestions = [{'cnpj': f[0], 'razao_social': f[1]} for f in fornecedores]
        return jsonify(suggestions)
    return jsonify([])


@home_bp.route('/home')
@login_required
def home():
    dataHoje = datetime.today().date()
    agendamentos = db.session.query(Agendamentos).filter(Agendamentos.date == dataHoje).all()
    return render_template('home.html', agendamentos=agendamentos)


@home_bp.route('/home/novoAgendamento', methods=['GET', 'POST'])
@login_required
def home_novoAgendamento():
    dataHoje = datetime.today().date()

    if request.method == 'GET':
        return render_template('home_novoAgendamento.html')
    
    elif request.method == 'POST':
        dateContato = dataHoje
        dateContatoResp = request.form['dateContatoRespForm']
        date = request.form['dateForm']
        deposito = request.form['depositoForm']
        cnpj = request.form['cnpjForm']
        fornecedor = request.form['fornecedorForm']
        numeroPedido = request.form['numeroPedidoForm']
        observacao = request.form['obsForm']
        volumePallets = request.form['volumePalletsForm']
        volumeCxs = request.form['volumeCxsForm']

        novoAgendamento = Agendamentos(
            dateContato = dateContato,
            dateContatoResp = dateContatoResp,
            date = date,
            deposito = deposito,
            cnpj = cnpj,
            fornecedor = fornecedor,
            numeroPedido = numeroPedido,
            observacao = observacao,
            volumePallets = volumePallets,
            volumeCxs = volumeCxs)
        
        flash('Agendamento incluido com sucesso.', 'agendSucess')

        db.session.add(novoAgendamento)
        db.session.commit()
    return redirect(url_for('home.home_novoAgendamento'))


@home_bp.route('/home/visualizarAgendamento')
@login_required
def home_visualizarAgendamento():
    dataFiltrada = request.args.get('date')

    if dataFiltrada:
        dataFiltrada = datetime.strptime(dataFiltrada, '%Y-%m-%d').date()
        agendamentos = db.session.query(Agendamentos).filter(Agendamentos.date == dataFiltrada).all()
    else:
        agendamentos = db.session.query(Agendamentos).all()
    return render_template('home_visualizarAgendamento.html', agendamentos=agendamentos)


@home_bp.route('/home/visualizarAgendamento/upload', methods=['POST'])
def home_visualizarAgendamento_upload():
    # Recupera o ID do agendamento do formulário
    agendamento_id = request.form.get('agendamento_id')
    
    # Verifica se o campo 'file' está presente nos arquivos enviados
    if agendamento_id and 'file' in request.files:
        file = request.files['file']
        
        # Verifica se o arquivo tem um nome e se é permitido
        if file.filename != '' and allowed_file(file.filename):
            # Lê o conteúdo do arquivo
            file_content = file.read()
            
            # Encontra o agendamento correspondente no banco de dados
            agendamento = db.session.query(Agendamentos).get(agendamento_id)
            if agendamento:
                # Atualiza o campo 'arquivo' com o conteúdo do arquivo
                agendamento.arquivo = file_content
                db.session.commit()  # Salva as alterações no banco de dados

    
    # Redireciona de volta à página de visualização de agendamentos
    return redirect(url_for('home.home_visualizarAgendamento'))


@home_bp.route('/home/visualizarAgendamento/arquivo/<int:agendamento_id>')
@login_required
def home_visualizarAgendamento_view_upload(agendamento_id):
    agendamento = db.session.query(Agendamentos).get(agendamento_id)
    if agendamento and agendamento.arquivo:
        return Response(
            agendamento.arquivo,
            mimetype='application/pdf',
            headers={"Content-Disposition": f"inline; filename=arquivo_{agendamento_id}.pdf"}
        )
    return redirect(url_for('home.home_visualizarAgendamento'))


@home_bp.route('/home/visualizarAgendamento/editar/<int:id>', methods=['GET', 'POST'])
@login_required
def home_visualizarAgendamento_editar(id):
    agendamentos = db.session.query(Agendamentos).filter_by(id=id).first()
    novaDiverg = db.session.query(Divergencias).filter_by(id=id).first()
    novaTroca = db.session.query(Trocas).filter_by(id=id).first()
    novaDevolucao = db.session.query(Devolucoes).filter_by(id=id).first()
    novoRecebimento = db.session.query(Recebimento).filter_by(id=id).first()

    if request.method == 'GET':
        novaDiverg = db.session.query(Divergencias).filter_by(id=id).first()
        novaTroca = db.session.query(Trocas).filter_by(id=id).first()
        novaDevolucao = db.session.query(Devolucoes).filter_by(id=id).first()
        novoRecebimento = db.session.query(Recebimento).filter_by(id=id).first()

        if not novaDiverg:
            novaDiverg = Divergencias()
            
        if not novaTroca:
            novaTroca = Trocas()

        if not novaDevolucao:
            novaDevolucao = Devolucoes()

        if not novoRecebimento:
            novoRecebimento = Recebimento()

        return render_template('editarAgendamento.html',
                               agendamentos = agendamentos,
                               novaDiverg = novaDiverg,
                               novaTroca = novaTroca,
                               novaDevolucao = novaDevolucao,
                               novoRecebimento = novoRecebimento)
    
    elif request.method == 'POST':
        agendamentos.dateContatoResp = request.form['dateContatoRespForm']
        agendamentos.date = request.form['dateForm']
        agendamentos.deposito = request.form['depositoForm']
        agendamentos.cnpj = request.form['cnpjForm']
        agendamentos.fornecedor = request.form['fornecedorForm']
        agendamentos.numeroPedido = request.form['numeroPedidoForm']
        agendamentos.observacao = request.form['obsForm']
        agendamentos.volumePallets = request.form['volumePalletsForm']
        agendamentos.volumeCxs = request.form['volumeCxsForm']

        novaDiverg = db.session.query(Divergencias).filter_by(id=id).first()
        novaTroca = db.session.query(Trocas).filter_by(id=id).first()
        novaDevolucao = db.session.query(Devolucoes).filter_by(id=id).first()
        novoRecebimento = db.session.query(Recebimento).filter_by(id=id).first()
        
        if novaDiverg:
            novaDiverg.diverg = bool(request.form.get('divergForm'))
            novaDiverg.divergMotivo = request.form['divergMotivoForm']
            novaDiverg.divergObs = request.form['divergObsForm']
        else:
            novaDiverg = Divergencias(
                id=id,
                diverg=bool(request.form.get('divergForm')),
                divergMotivo=request.form['divergMotivoForm'],
                divergObs=request.form['divergObsForm']
            )
            db.session.add(novaDiverg)

        if novaTroca:
            novaTroca.trocas = bool(request.form.get('trocasForm'))
            novaTroca.trocasObs = request.form['trocasObsForm']
            novaTroca.trocasValor = request.form['trocasValorForm']
        else:
            novaTroca = Trocas(
                id=id,
                trocas=bool(request.form.get('trocasForm')),
                trocasObs=request.form['trocasObsForm'],
                trocasValor='0'
            )
            db.session.add(novaTroca)

        if novaDevolucao:
            novaDevolucao.devolucoes = bool(request.form.get('devolucoesForm'))
            novaDevolucao.devolucoesObs = request.form['devolucoesObsForm']
            novaDevolucao.devolucoesValor = request.form['devolucoesValorForm']
        else:
            novaDevolucao = Devolucoes(
                id=id,
                devolucoes = bool(request.form.get('devolucoesForm')),
                devolucoesObs = request.form['devolucoesObsForm'],
                devolucoesValor = '0'
            )
            db.session.add(novaDevolucao)

        if novoRecebimento:
            novoRecebimento.recebimento = bool(request.form.get('recebimentoForm'))
            novoRecebimento.recebimentObs = request.form['recebimentObsForm']
            novoRecebimento.recebQtdePallets = request.form['recebQtdePalletsForm']
            novoRecebimento.recebQtdeChapas = request.form['recebQtdeChapasForm']
        else:
            novoRecebimento = Recebimento(
                id=id,
                recebimento = bool(request.form.get('recebimentoForm')),
                recebimentObs = request.form['recebimentObsForm'],
                recebQtdePallets = request.form['recebQtdePalletsForm'],
                recebQtdeChapas = request.form['recebQtdeChapasForm']
            )
            db.session.add(novoRecebimento)

        db.session.commit()
        return redirect (url_for('home.home_visualizarAgendamento'))


@home_bp.route('/home/visualizarAgendamento/deletar/<int:id>')
@login_required
def home_visualizarAgendamento_deletar(id):
    agendamentos = db.session.query(Agendamentos).filter_by(id=id).first()
    db.session.delete(agendamentos)
    db.session.commit()
    return redirect (url_for('home.home_visualizarAgendamento'))

blueprints/login.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_login import LoginManager, login_user, login_required, logout_user, current_user
from db import db
from models import User

login_bp = Blueprint('login', __name__)

lm = LoginManager()

@lm.user_loader
def userLoader(id):
    user = db.session.query(User).filter_by(id=id).first()
    return user


@login_bp.route('/login', methods = ['GET', 'POST'])
def login():
    if request.method == 'GET':
        return render_template('login.html')
    
    elif request.method == 'POST':
        userEmail = request.form['userEmailForm']
        userSenha = request.form['userSenhaForm']

        user = db.session.query(User).filter_by(userEmail=userEmail, userSenha=userSenha).first()

        if not user:
            flash('Email ou senha incorretos.', 'error')
            return redirect(url_for('login.login'))
    
        login_user(user)
        return redirect(url_for('home.home'))


@login_bp.route('/login/createAccount', methods=['GET', 'POST'])
def createAccount():
    if request.method == 'GET':
        return render_template('login_createAccount.html')
    
    elif request.method == 'POST':
        userNome = request.form['userNomeForm']
        userEmail = request.form['userEmailForm']
        userSenha = request.form['userSenhaForm']
        userSenhaConfirm = request.form['userSenhaConfirmForm']

        if userSenha != userSenhaConfirm:
            flash('As senhas devem ser iguais', 'error')
            return redirect(url_for('login.createAccount'))
        
        userNomeExist = db.session.query(User).filter_by(userNome=userNome).first()
        if userNomeExist:
            flash('Nome em uso', 'error')
            return redirect(url_for('login.createAccount'))
        
        userEmailExist = db.session.query(User).filter_by(userEmail=userEmail).first()
        if userEmailExist:
            flash('Email em uso', 'error')
            return redirect(url_for('login.createAccount'))

        newUser = User(
            userNome = userNome,
            userEmail = userEmail,
            userSenha = userSenha
        )

        db.session.add(newUser)
        db.session.commit()
        flash('Conta criada com sucesso', 'success')

        login_user(newUser)
    return redirect(url_for('login.login'))


@login_bp.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('login.login'))

templates/base.html
<!DOCTYPE html>

<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}{% endblock %}</title>
        {% block css %}{% endblock %}
        <link rel="stylesheet" href="{{ url_for('static', filename='css/home.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/flash.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='icons/bootstrap-icons.css') }}">
    </head>

    <body>
        <div class="principal">
            <div class="sidebar">
                <div class="info_user">
                    <div class="profile_picture">
                        <i class="bi bi-person-badge"></i>
                    </div>
                    <span id="user-name">{{ current_user.userNome }}</span>
                </div>
                <div class="menu">
                    <ul>
                        <li>
                            <a href="{{ url_for('home.home') }}">
                                <i class="bi bi-house"></i>
                                <span>Home</span>
                            </a>
                        </li>
                        <li>
                            <a href="{{ url_for('home.home_novoAgendamento') }}">
                                <i class="bi bi-calendar2-plus"></i>
                                <span>Novo Agendamento</span>
                            </a>
                        </li>
                        <li>
                            <a href="{{ url_for('home.home_visualizarAgendamento') }}">
                                <i class="bi bi-calendar2-week"></i>
                                <span>Visualizar Agendamento</span>
                            </a>
                        </li>
                    </ul>
                </div>
                <a href="{{ url_for('login.logout') }}" class="sidebarBtnLogout">Logout</a>
            </div>

            <div class="content">
                {% block content %}
                
                {% endblock %}
            </div>
        </div>
        {% block scripts %}<script src="{{ url_for('static', filename='js/suggestions.js') }}"></script>{% endblock %}
    </body>

</html>

templates/editarAgendamento.html
{% extends "base.html" %}

{% block title %}Editar{% endblock %}

{% block content %}
    <form action="{{ url_for('home.home_visualizarAgendamento_editar', id=agendamentos.id) }}" method="post" class="formE">
        <div class="formEdivs">
            <div class="formEdiv">
                <h3>Agendamento</h3>
                <label>Responsável</label>
                <input type="text" name="dateContatoRespForm" value="{{ agendamentos.dateContatoResp }}">
                <label>Data de Entrega</label>
                <input type="date" name="dateForm" value="{{ agendamentos.date }}" required>
                <label>Depósito</label>
                <input type="text" name="depositoForm" value="{{ agendamentos.deposito }}" required>
                <label>CNPJ</label>
                <input type="text" id="cnpj" name="cnpjForm" value="{{ agendamentos.cnpj }}" required>
                <div id="cnpj-suggestions" class="suggestions-list"></div>
                <label>Fornecedor</label>
                <input type="text" id="fornecedor" name="fornecedorForm" value="{{ agendamentos.fornecedor }}" required>
                <div id="fornecedor-suggestions" class="suggestions-list"></div>
                <label>N° Pedido</label>
                <input type="text" id="numeroPedido" name="numeroPedidoForm" value="{{ agendamentos.numeroPedido }}" required>
                <label>Observação</label>
                <input type="text" name="obsForm" value="{{ agendamentos.observacao }}">
                <label>Volume Pallets</label>
                <input type="text" name="volumePalletsForm" value="{{ agendamentos.volumePallets }}">
                <label>Volume Cxs</label>
                <input type="text" name="volumeCxsForm" value="{{ agendamentos.volumeCxs }}">
            </div>

            <div class="formEdiv">
                <h3>Divergências</h3>
                <label>Divergência</label>
                <div class="formEdivCheckbox">
                    <input type="checkbox" name="divergForm" {% if novaDiverg.diverg %}checked{% endif %}>
                </div>
                <label>Motivo</label>
                <input type="text" name="divergMotivoForm" value="{{ novaDiverg.divergMotivo }}">
                <label>Observação</label>
                <input type="text" name="divergObsForm" value="{{ novaDiverg.divergObs }}">
            </div>

            <div class="formEdiv">
                <h3>Trocas</h3>
                <label>Trocas</label>
                <div class="formEdivCheckbox">
                    <input type="checkbox" name="trocasForm" {% if novaTroca.trocas %}checked{% endif %}>
                </div>
                <label>Valor Trocas</label>
                <input type="text" name="trocasValorForm" value="{{ novaTroca.trocasValor if novaTroca else '' }}">
                <label>Observação</label>
                <input type="text" name="trocasObsForm" value="{{ novaTroca.trocasObs if novaTroca else '' }}">

                <h3>Devoluções</h3>
                <label>Devoluções</label>
                <div class="formEdivCheckbox">
                    <input type="checkbox" name="devolucoesForm" {% if novaDevolucao.devolucoes %}checked{% endif %}>
                </div>
                <label>Valor Devolução</label>
                <input type="text" name="devolucoesValorForm" value="{{ novaDevolucao.devolucoesValor if novaDevolucao else '' }}">
                <label>Observação</label>
                <input type="text" name="devolucoesObsForm" value="{{ novaDevolucao.devolucoesObs if novaDevolucao else '' }}">
            </div>

            <div class="formEdiv">
                <h3>Recebimento</h3>
                <label>Recebimento</label>
                <div class="formEdivCheckbox">
                    <input type="checkbox" name="recebimentoForm" {% if novoRecebimento.recebimento %}checked{% endif %}>
                </div>
                <label>Observação</label>
                <input type="text" name="recebimentObsForm" value="{{ novoRecebimento.recebimentObs if novoRecebimento else '' }}">
                <label>Qtde Pallets</label>
                <input type="text" name="recebQtdePalletsForm" value="{{ novoRecebimento.recebQtdePallets if novoRecebimento else '' }}">
                <label>Qtde Cxs</label>
                <input type="text" name="recebQtdeChapasForm" value="{{ novoRecebimento.recebQtdeChapas if novoRecebimento else '' }}">
            </div>
        </div>

        <div class="formEbutton">
            <button type="submit" class="btn-v">Atualizar Dados</button>
        </div>
    </form>
{% endblock %}

{% block scripts %}<script src="{{ url_for('static', filename='js/suggestions.js') }}"></script>{% endblock %}

templates/home.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block content %}

    <div>
        <h1>Agendamentos de Hoje:</h1>
    </div>

    <table>

        <tr>
            <th>ID</th>
            <th>Date</th>
            <th>CNPJ</th>
            <th>Fornecedor</th>
            <th>N° Pedido</th>
            <th></th>
        </tr>

        {% for agendamento in agendamentos %}
        <tr>
            <td>{{ agendamento.id }}</td>
            <td>{{ agendamento.date }}</td>
            <td>{{ agendamento.cnpj }}</td>
            <td>{{ agendamento.fornecedor }}</td>
            <td>{{ agendamento.numeroPedido }}</td>
            <td>
                <a href="{{ url_for('home.home_visualizarAgendamento_editar', id=agendamento.id) }}" class="btn-v">
                    <span>Editar</span>                   
                </a>
            </td>  
        </tr>
        {% endfor %}

    </table>
{% endblock %}

templates/home_novoAgendamento.html
{% extends "base.html" %}

{% block title %}Novo Agendamento{% endblock %}

{% block content %}
    <form action="{{ url_for('home.home_novoAgendamento') }}" method="post" class="formN">
        <div>
            <h3>Incluir Agendamento</h3>
        </div>
        
        <div class="formNdivs">
            <div class="formNdiv">
                <label class="labelN">Data Entrega</label>
                <input type="date" name="dateForm" required>
                <label class="labelN">Responsável</label>
                <input type="text" name="dateContatoRespForm">
                <label class="labelN">CNPJ</label>
                <input type="text" id="cnpj" name="cnpjForm" required>
                <div id="cnpj-suggestions" class="suggestions-list"></div>
                <label class="labelN">Fornecedor</label>
                <input type="text" id="fornecedor" name="fornecedorForm" required>
                <div id="fornecedor-suggestions" class="suggestions-list"></div>
                <label class="labelN">N° Pedido</label>
                <input type="text" id="numeroPedido" name="numeroPedidoForm" required>
            </div>

            <div class="formNdiv">
                <label class="labelN">Depósito</label>
                <select name="depositoForm" required>
                    <option value="SED">SED</option>
                    <option value="CDA">CDA</option>
                    <option value="ACC">ACC</option>
                </select>
                <label class="labelN">Observação</label>
                <input type="text" name="obsForm">
                <label class="labelN">Volume Pallets</label>
                <input type="text" name="volumePalletsForm">
                <label class="labelN">Volume Cxs</label>
                <input type="text" name="volumeCxsForm">
            </div>
        </div>

        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category, message in messages %}
                    <p class="flashSucess {{ category }}">{{ message }}</p>
                {% endfor %}
            {% endif %}
        {% endwith %}
    

        <div class="formNbutton">
            <button type="submit">Agendar</button>
        </div>
    </form>
{% endblock %}

{% block scripts %}<script src="{{ url_for('static', filename='js/suggestions.js') }}"></script>{% endblock %}

templates/home_visualizarAgendamento.html
{% extends "base.html" %}

{% block title %}Visualizar{% endblock %}

{% block content %}
    <form action="{{ url_for('home.home_visualizarAgendamento') }}" method="get" class="formV">
        <label>Selecione a data específica que deseja visualizar:</label>
        <input type="date" id="date" name="date">
        <button type="submit" class="btn-v">Filtrar</button>
    </form>

    <div class="tableView">
        <table>
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Date</th>
                    <th>Fornecedor</th>
                    <th>N° Pedido</th>
                    <th>Distribuição</th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            
            <tbody>
                {% for agendamento in agendamentos %}
                <tr>
                    <td>{{ agendamento.id }}</td>
                    <td>{{ agendamento.date }}</td>
                    <td>{{ agendamento.fornecedor }}</td>
                    <td>{{ agendamento.numeroPedido }}</td>
                    <td>
                        <form action="{{ url_for('home.home_visualizarAgendamento_upload') }}" method="post" enctype="multipart/form-data">
                            <input type="hidden" name="agendamento_id" value="{{ agendamento.id }}">

                            {% if agendamento.arquivo %}
                                <a href="{{ url_for('home.home_visualizarAgendamento_view_upload', agendamento_id=agendamento.id) }}" target="_blank" class="btn-v">
                                    <i class="bi bi-eye"></i>
                                    <span>Ver</span>
                                </a>
                            {% else %}
                                <input type="file" name="file">
                                <input type="submit" value="Upload">
                            {% endif %}
                        </form>
                    </td>
                    <td>
                        <a href="{{ url_for('home.home_visualizarAgendamento_editar', id=agendamento.id) }}" class="btn-v">
                            <span>Editar</span>                   
                        </a>
                    </td>    
                    <td>
                        <a href="{{ url_for('home.home_visualizarAgendamento_deletar', id=agendamento.id) }}" class="btn-v">
                            <span>Excluir</span>                    
                        </a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

templates/login.html
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/Login.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='icons/bootstrap-icons.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/flash.css') }}">
</head>

<body>
    <form action="{{ url_for('login.login') }}" method="post">
        <h3>Login:</h3>

        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category, message in messages %}
                    {% if 'error' in category %}
                        <p class="flashError">{{ message }}</p>
                    {% elif 'success' in category %}
                        <p class="flashSuccess">{{ message }}</p>
                    {% endif %}
                {% endfor %}
            {% endif %}
        {% endwith %}

        <div>
            <label>
                <input class="input" type="email" name="userEmailForm" required>
                <span>Digite seu Email:</span>
            </label>
        </div>

        <div>
            <label>
                <input class="input" type="password" name="userSenhaForm" required>
                <span>Digite sua Senha:</span>
            </label>
        </div>

        <button class="submit">Entrar</button>

        <p class="signin">Esqueceu sua Senha?
            <a href="#">Recuperar Senha</a>
        </p>

        <p class="signin">Não possuí uma conta?
            <a href="{{ url_for('login.createAccount') }}">Criar Conta</a>
        </p>
    </form>
</body>
</html>

templates/login_createAccount.html
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Criar Conta</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/createAccount.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/flash.css') }}">
</head>

<body>
    <form class="form" action="{{ url_for('login.createAccount') }}" method="post">
        <p class="title">Registre-se:</p>

        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category, message in messages %}
                    <p class="flashError {{ category }}">{{ message }}</p>
                {% endfor %}
            {% endif %}
        {% endwith %}

        <label>
            <input class="input" type="text" name="userNomeForm" required>
            <span>Nome:</span>
        </label>
        <label>
            <input class="input" type="email" name="userEmailForm" required>
            <span>Seuemail@supernicolini.com.br:</span>
        </label>
        <label>
            <input class="input" type="password" name="userSenhaForm" required>
            <span>Senha:</span>
        </label>
        <label>
            <input class="input" type="password" name="userSenhaConfirmForm" required>
            <span>Confirme sua Senha:</span>
        </label>

        <button class="submit">Criar Conta</button>

        <p class="signin">Já possuí uma conta? <a href="{{ url_for('login.login') }}">Entrar</a></p>
    </form>
</body>

</html>